-- AlterTable
ALTER TABLE "user_stats" ADD COLUMN     "activeSessions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rookieRating" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
ADD COLUMN     "totalEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalRookieSessions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalSpent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalTutoSessions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "tpointsBalance" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "tutoRating" DOUBLE PRECISION NOT NULL DEFAULT 5.0;
